In [1]:
import seaborn as sns
import pandas as pd
import operator 
import time 
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [2]:
tm = pd.read_csv('../data/TEIS_Monthly.csv')

In [3]:
tr = pd.read_csv('../data/TEIS_Recent.csv')

In [4]:
teis_merge = pd.merge(tm,tr, how = 'outer')

In [5]:
teis_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 191563 entries, 0 to 191562
Data columns (total 36 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   POE                          191563 non-null  object
 1   Child ID                     191563 non-null  int64
 2   DOB                          191563 non-null  object
 3   County Name                  191555 non-null  object
 4   County SES                   113251 non-null  object
 5   Child Phase                  191563 non-null  object
 6   Active                       191563 non-null  object
 7   Service Coordinator          191562 non-null  object
 8   Notification/ Referral Date  113256 non-null  object
 9   Parent Consent Date          127024 non-null  object
 10  Referral Source Type Name    191563 non-null  object
 11  Initial Eligibility          107264 non-null  object
 12  Initial Eligibility Date     107264 non-null  object
 13  Initial IFSP Date            53185 non-null   object
 14  Latest IFSP Date             51996 non-null   object
 15  Exit Reason                  106768 non-null  object
 16  Exit Date                    106768 non-null  object
 17  Fiscal Year                  113256 non-null  object
 18  Notification Month           113256 non-null  object
 19  Tenn Region                  113256 non-null  object
 20  Referral Count               113256 non-null  float64
 21  Evaluation Count             59469 non-null   float64
 22  Eligibility Count            40762 non-null   float64
 23  IFSP Count                   8010 non-null    float64
 24  Service Coordinator Counter  113256 non-null  float64
 25  Fiscal Year.1                113256 non-null  float64
 26  Child Count                  113256 non-null  float64
 27  2012 Child Count             0 non-null       float64
 28  2013 Child Count             0 non-null       float64
 29  third DOB                    113256 non-null  object
 30  Late Referral                2829 non-null    float64
 31  Qtr                          113256 non-null  float64
 32   QTR                         113256 non-null  object
 33  Referral Source Category     113256 non-null  object
 34  County SES                   96576 non-null   object
 35  Notification Date            96580 non-null   object
dtypes: float64(11), int64(1), object(24)
memory usage: 54.1+ MB

In [6]:
teis_merge.count()

POE                            191563
Child ID                       191563
DOB                            191563
County Name                    191555
County SES                     113251
Child Phase                    191563
Active                         191563
Service Coordinator            191562
Notification/ Referral Date    113256
Parent Consent Date            127024
Referral Source Type Name      191563
Initial Eligibility            107264
Initial Eligibility Date       107264
Initial IFSP Date               53185
Latest IFSP Date                51996
Exit Reason                    106768
Exit Date                      106768
Fiscal Year                    113256
Notification Month             113256
Tenn Region                    113256
Referral Count                 113256
Evaluation Count                59469
Eligibility Count               40762
IFSP Count                       8010
Service Coordinator Counter    113256
Fiscal Year.1                  113256
Child Count                    113256
2012 Child Count                    0
2013 Child Count                    0
third DOB                      113256
Late Referral                    2829
Qtr                            113256
 QTR                           113256
Referral Source Category       113256
County SES                      96576
Notification Date               96580
dtype: int64

In [7]:
tm.count()

POE                            113256
Child ID                       113256
DOB                            113256
County Name                    113251
County SES                     113251
Child Phase                    113256
Active                         113256
Service Coordinator            113255
Notification/ Referral Date    113256
Parent Consent Date             58101
Referral Source Type Name      113256
Initial Eligibility             40762
Initial Eligibility Date        40762
Initial IFSP Date                8010
Latest IFSP Date                 7983
Exit Reason                     39366
Exit Date                       39366
Fiscal Year                    113256
Notification Month             113256
Tenn Region                    113256
Referral Count                 113256
Evaluation Count                59469
Eligibility Count               40762
IFSP Count                       8010
Service Coordinator Counter    113256
Fiscal Year.1                  113256
Child Count                    113256
2012 Child Count                    0
2013 Child Count                    0
third DOB                      113256
Late Referral                    2829
Qtr                            113256
 QTR                           113256
Referral Source Category       113256
dtype: int64

In [8]:
tr.count()

POE                          96580
Child ID                     96580
DOB                          96580
County Name                  96576
County SES                   96576
Child Phase                  96580
Active                       96580
Service Coordinator          96579
Notification Date            96580
Parent Consent Date          70026
Referral Source Type Name    96580
Initial Eligibility          68221
Initial Eligibility Date     68221
Initial IFSP Date            45493
Latest IFSP Date             44331
Exit Reason                  85194
Exit Date                    85194
dtype: int64

In [9]:
teis_merge.groupby('Child ID').count()

,POE,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification/ Referral Date,Parent Consent Date,Referral Source Type Name,...,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category,County SES,Notification Date
Child ID,,,,,,,,,,,,,,,,,,,,,
104085,1,1,1,1,1,1,0,1,0,1,...,1,0,0,1,1,1,1,1,1,1
350065,1,1,1,1,1,1,1,1,0,1,...,1,0,0,1,1,1,1,1,1,1
351755,2,2,2,1,2,2,2,1,2,2,...,1,0,0,1,0,1,1,1,1,1
353800,1,1,1,1,1,1,1,1,0,1,...,1,0,0,1,1,1,1,1,1,1
353805,2,2,2,1,2,2,2,1,2,2,...,1,0,0,1,0,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531592,1,1,1,0,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,1,1
531593,1,1,1,0,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,1,1
531594,1,1,1,0,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,1,1
531595,1,1,1,0,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,1,1
531596,1,1,1,0,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,1,1

In [10]:
tm.groupby('Child ID').count()

,POE,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification/ Referral Date,Parent Consent Date,Referral Source Type Name,...,Service Coordinator Counter,Fiscal Year.1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
Child ID,,,,,,,,,,,,,,,,,,,,,
104085,1,1,1,1,1,1,0,1,0,1,...,1,1,1,0,0,1,1,1,1,1
350065,1,1,1,1,1,1,1,1,0,1,...,1,1,1,0,0,1,1,1,1,1
351755,1,1,1,1,1,1,1,1,1,1,...,1,1,1,0,0,1,0,1,1,1
353800,1,1,1,1,1,1,1,1,0,1,...,1,1,1,0,0,1,1,1,1,1
353805,1,1,1,1,1,1,1,1,1,1,...,1,1,1,0,0,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
529587,1,1,1,1,1,1,1,1,1,1,...,1,1,1,0,0,1,0,1,1,1
529597,1,1,1,1,1,1,1,1,0,1,...,1,1,1,0,0,1,0,1,1,1
529599,1,1,1,1,1,1,1,1,0,1,...,1,1,1,0,0,1,1,1,1,1
529606,1,1,1,1,1,1,1,1,0,1,...,1,1,1,0,0,1,0,1,1,1
529609,1,1,1,1,1,1,1,1,0,1,...,1,1,1,0,0,1,0,1,1,1

In [11]:
slicertm = tm[['Child ID', 'POE', 'Notification/ Referral Date','Fiscal Year', 'County Name','Referral Year']]
slicertm

KeyError: "['Referral Year'] not in index"

In [ ]:
dups_tm = slicertm.loc[slicertm.duplicated(subset='Child ID', keep=False)]
dups_tm

In [ ]:
dups_tm.sort_values(by = "Child ID")

In [ ]:
dups_tm.groupby('Child ID').count()

In [ ]:
dups_tm.groupby(['POE', 'Child ID']).count()

In [ ]:
dups_tm.groupby('Fiscal Year').count()

In [ ]:
dups_double = dups_tm.groupby(['POE', 'Child ID'], as_index = False).count()
dups_370631 = dups_double.loc[dups_double['Child ID']== 370631]
dups_370631

In [ ]:
dups_tm_child = dups_tm.groupby('Child ID', as_index = False).count()
dups_tm_child.value_counts('Child ID')

In [ ]:
tm['Referral Year'] = tm['Notification/ Referral Date'].str[-4:]
print(tm)

In [ ]:
tm.count()

In [ ]:
tm.head(9000)

In [ ]:
tm['IFSP Count']